name: Deploy to GitHub Pages

on:
  push:
    branches:
      - gh-pages  # Change this to your main branch if it's different

permissions:
  contents: write  # Allows the workflow to write to the repository

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run python file
        run: python pytho.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages  # Specify the branch to deploy to
